<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="da" lang="da">
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<!-- STYLE SHEETS -->
	<link href="/media/global.css?v=<?=VERSION?>" media="screen" rel="stylesheet" type="text/css" />
	<!--[if lt IE 7]><style type="text/css">#master_wrapper{height:100%;}</style><![endif]-->
	<link rel="shortcut icon" type="image/x-icon" href="/media/images/gfx/favicon.ico" />

	<script src="/js/mootools-1.2.4-core-nc.js" type="text/javascript"></script>
	<script src="/js/mootools-1.2.4.2-more.js" type="text/javascript"></script>

	<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-21805458-1']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	</script>

</head>
<body>

<div class="body_bg"></div>
<div id="master_wrapper">


	<section id="content">
		<h1>Vi beklager</h1>
		<p>Vores database er desværre nede. Vi arbejder på sagen!</p>
	</section>

	<div id="clear_footer"></div>
</div>

<footer>
	<div class="footer_content corners5px">
		<span class="left">
			Appvice.dk <?=date('Y')?>
		</span>
		<span class="right">

			E-mail: <a href="mailto:mads@appvice.dk">mads@appvice.dk</a>&nbsp;&nbsp;|&nbsp;&nbsp;Telefon: 31 31 95 31 &nbsp;&nbsp;
		</span>
	</div>
</footer>

</body>
</html>
