<!DOCTYPE html>
<!-- /ht Paul Irish - http://front.ie/j5OMXi -->
<!--[if lt IE 7 ]> <html class="no-js ie6" xmlns="http://www.w3.org/1999/xhtml" xml:lang="da" lang="da"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" xmlns="http://www.w3.org/1999/xhtml" xml:lang="da" lang="da"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" xmlns="http://www.w3.org/1999/xhtml" xml:lang="da" lang="da"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" xmlns="http://www.w3.org/1999/xhtml" xml:lang="da" lang="da"> <!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?= $this->headTitle() ?>
		<?= $this->headMeta() ?>

		<!-- /ht Andy Clarke - http://front.ie/lkCwyf -->
		<meta http-equiv="cleartype" content="on" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

		<link rel="shortcut icon" type="/image/x-icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" href="apple-touch-icon.png">


		<?= $this->headLink() ?>

		<!-- /ht Jeremy Keith - http://front.ie/mLXiaS -->
		<link rel="stylesheet" href="/css/global.css" media="all">
		<link rel="stylesheet" href="/css/layout.css" media="all and (min-width: 48.236em)">
		<link rel="stylesheet" href="/css/admin.css" media="all">
		<link rel="stylesheet" href="/css/datepicker.css" media="all">
		<!-- 30em + (1.618em * 2) = 33.236em / Eliminates potential of horizontal scrolling in most cases -->

		<!--[if (lt IE 9) & (!IEMobile)]>
		<link rel="stylesheet" href="/media/layout.css" media="all">
		<![endif]-->

		<script src="/js/mootools-core-1.4.5-full-nocompat.js" type="text/javascript"></script>
		<script src="/js/mootools-more-1.4.0.1.js" type="text/javascript"></script>

		<?= $this->headScript() ?>
		<?= $this->headStyle() ?>

		<script type="text/javascript">
				(function() {
						var link_element = document.createElement("link"),
								s = document.getElementsByTagName("script")[0];
						if (window.location.protocol !== "http:" && window.location.protocol !== "https:") {
								link_element.href = "http:";
						}
						link_element.href += "//fonts.googleapis.com/css?family=Montserrat:400,700";
						link_element.rel = "stylesheet";
						link_element.type = "text/css";
						s.parentNode.insertBefore(link_element, s);
				})();
		</script>


</head>
<body>
<div id="master_wrapper" class="admin table_wrapper">
	<header>
		<div class="content">
			<div class="logo"><a href="/" style="float:left;"></a>
			</div>
			<nav >
				<ul id="navigation" class="cf">
					<?php
					$menu = array(
						//'adminusers' => 'Brugere',
						'index' => 'Forside',
						'instances' => 'Instances',
						'statistics' => 'Statistik'
					);
					foreach($menu as $m => $name){
						?>
						<li><a href="/admin/<?=$m?>" <?=Zend_Controller_Front::getInstance()->getRequest()->getActionName() == $m ? ' class="selected"' : ''?>><?=htmlspecialchars(ucfirst($name))?></a></li>
						<?php
					}
					?>
				</ul>



				<div style="clear:both;"></div>
			</nav>
			<div class="header_functions corners5px">

			</div>
		</div>
	</header>

	<section id="content" class="cf">
		<div class="content">
			<?php echo $this->layout()->content; ?>
		</div>
	</section>

	<footer>
		<div class="footer_content corners5px">
			<span class="left">
				Copyright <?=$_SERVER['SERVER_NAME']?> <?=date('Y')?>
			</span>
			<span class="right">

				E-mail: <a href="mailto:mads@appvice.dk">mads@appvice.dk</a>&nbsp;&nbsp;|&nbsp;&nbsp;Telefon: 31 31 95 31&nbsp;&nbsp;
			</span>
		</div>
	</footer>


</div>
</body>
</html>
