<h1>Admin</h1>
<?php
if(isset($this->message)){
	switch($this->message){
		case 'locker_deleted':
			?>
			<h2 class="message">Skabet er slettet</h2>
			<?php
			break;
		default:
			?>
			<h2 class="message"><?=htmlspecialchars($this->message)?></h2>
			<?php
			break;
	}
}
?>


<span>System dato: <?=$this->system_date?></span>

<table class="section_table">
	<tr>
		<th colspan="<?=$this->section_count?>">
			Total (<?=$this->stat['used']?>/<?=$this->stat['total']?>)
		</th>
	</tr>
	<tr>
		<?php
		foreach($this->stat['floors'] as $floor_name => $floor){
			?>
			<td colspan="<?=count($floor['sections'])?>"><a href="/admin/lockers/floor/<?=urlencode($floor_name)?>"><?=htmlspecialchars($floor_name ? $floor_name : '[no name]')?></a> (<?=$floor['used']?>/<?=$floor['total']?>)</td>
			<?php
		}
		?>
	</tr>
	<tr>
		<?php
			foreach($this->stat['floors'] as $floor_name => $floor){
				foreach($floor['sections'] as $section_name => $section){
					?>
					<td><a href="/admin/lockers/floor/<?=urlencode($floor_name)?>/section/<?=urlencode($section_name)?>"><?=htmlspecialchars($section_name ? $section_name : '[no name]')?></td>
					<?php
				}
			}
		?>
	</tr>
	<tr>
		<?php
			foreach($this->stat['floors'] as $floor){
				foreach($floor['sections'] as $section_name => $section){
					?>
					<td>(<?=$section['used']?>/<?=$section['total']?>)</td>
					<?php
				}
			}
		?>
	</tr>
</table>
<?php

	//Zend_Debug::dump($this->stat);

	//Zend_Debug::dump($this->total_orders);
?>

<form method="GET" action="/admin/lockers" class="search_form" style="">

	<button type="submit">Søg</button>
	<div class="bfc"><input type="text" placeholder="fx. 1234 eller 1234-1456" name="search"/>
	</div>
</form>
