<h1>Ret i skab</h1>

<?php
	if(isset($this->err)){
		switch($this->err){
			case 'locker_exists':
				?>
				<h2 class="message">Kunne ikke gemme skab med skabsnummer <?=htmlspecialchars($this->new_lockerId)?> da der allerede existerer et skab med dette skabsnummer.</h2>
				<?php
				break;
		}
	}

	if(isset($this->message)){
		switch($this->message){
			case 'saved':
				?>
				<h2 class="message">Skabet er gemt</h2>
				<?php
				break;
			case 'released':
				?>
				<h2 class="message">Skabet er frigivet</h2>
				<?php
				break;
			default:
				?>
				<h2 class="message"><?=htmlspecialchars($this->message)?></h2>
				<?php
				break;
		}
	}
?>

<form method="POST" action="?">
	<div class="form_item">
		<label>Skabsnummer</label>
		<input type="number" placeholder="skabsnummer" name="new_lockerId" value="<?=str_pad($this->locker->lockerId,4,'0',STR_PAD_LEFT)?>" />
	</div>

	<div class="form_item">
		<label>Etage</label>
		<input type="text" list="floors" placeholder="Etage" name="floor" value="<?=htmlspecialchars($this->locker->floor)?>" />
		<datalist id="floors">
			<?php
				foreach($this->floors as $floor){
					?>
					<option><?=htmlspecialchars($floor['name'])?></option>
					<?php
				}
			?>
		</datalist>
	</div>

	<div class="form_item">
		<label>Sektion</label>
		<input type="text" placeholder="sektion" list="sections" name="section" value="<?=htmlspecialchars($this->locker->section)?>" />
		<datalist id="sections">
			<?php
				foreach($this->sections as $section){
					?>
					<option value="<?=htmlspecialchars($section['name'])?>"><?=htmlspecialchars($section['name'])?></option>
					<?php
				}
			?>
		</datalist>
	</div>

	<div class="form_item">
		<label>Blok</label>
		<input type="text" placeholder="blok" list="blocks" name="block" value="<?=htmlspecialchars($this->locker->block)?>" />
		<datalist id="blocks">
			<?php
				foreach($this->blocks as $block){
					?>
					<option><?=htmlspecialchars($block['name'])?></option>
					<?php
				}
			?>
		</datalist>
	</div>

	<?php
		if($this->locker->lockerId){
			?>
			<div class="form_item">
				<label>Reserveret til</label>
				<div class="data"><?=htmlspecialchars($this->locker->release)?></div>
			</div>
			<div class="form_item">
				<label>Nuværende kode</label>
				<div class="data"><?=str_pad($this->code, 4, '0', STR_PAD_LEFT) ?></div>
			</div>
			<?php
		}
	?>



	<div class="form_item">
		<button type="submit">Gem</button>
		<?php
		if($this->locker->lockerId){
			?>
			<button type="button" onclick="if(confirm('Er du sikker på at du vil slette dette skab helt?')){window.location='?do=delete';}">Slet skab</button>
			<?php

			if(strtotime($this->locker->release) > time()){
			?>
			<button type="button" onclick="if(confirm('Er du sikker på at du vil fjerne nuværende reservation af dette skab?')){window.location='?do=release';}">Frigør skab</button>
			<?php
			}
		}?>
	</div>

</form>

<hr />

<?php
	if($this->locker->lockerId){
		?>
		<h2>Ordre med dette skab</h2>
		<?php

		if(!count($this->orders)){
			?><h2 class="message">Ingen ordre</h2><?php
		} else {
			?>
			<div class="order_header">
				<div class="orderId">Ordre ID</div>
				<div class="created">Oprettet</div>
				<div class="lock_date">Skabs dato</div>
				<div class="status">Status</div>
				<div class="cancel"></div>
			</div>
			<?php
		}
		foreach($this->orders as $order){
			?>
			<div class="order">
				<div class="orderId"><?=htmlspecialchars($order['orderId'])?></div>
				<div class="created"><?=htmlspecialchars($order['created'])?></div>
				<div class="lock_date"><?=htmlspecialchars($order['lock_date'])?></div>
				<div class="status"><?=htmlspecialchars($order['status'])?>&nbsp;</div>
				<div class="payment_type"><?=htmlspecialchars($order['payment_type'])?>&nbsp;</div>
				<?php
				if($order['status'] == 'paid' && in_array($order['payment_type'],array('MobilePay','DIBS'))){
					?>
					<a class="cancel" onclick="refundOrder(this);return false;" href="/admin/order/order_id/<?=$order['orderId']?>?do=cancel">cancel</a>
					<?php
				} else {
					?>
					<div class="cancel">&nbsp;</div>
					<?php
				}
				?>

			</div>
			<?php
		}
	}
?>
<script>
	window.refundOrder = function(el){
		var uri = $(el).get('href');

		var r = new Request({
			url:uri,
			onComplete:function(r){
				alert(r);
				window.location.reload();
			}
		}).send();
	};
</script>
