<h1>Lockers</h1>

<div class="cf">
	<a class="button" href="/admin/locker/locker_id/new">Opret nyt skab</a>
</div>

<?php
	if(isset($this->message)){
		?><h2 class="message"><?=htmlspecialchars($this->message)?></h2>
		<?php
	}
	if(!count($this->lockers)){
		?>
		<h2 class="message">Ingen skabe matcher søgningen.</h2>
		<?php
	} else {
		?>
		<div class="locker_header">
			<div class="locker_id">Skabsnr.</div>
			<div class="floor">Etage</div>
			<div class="section">Sektion</div>
			<div class="block">Blok</div>
			<div class="status">Status</div>
			<div class="order_count">#ordre</div>
			<div class="release">Fri</div>
			<div class="edit"></div>
		</div>
		<?php
	}

	foreach($this->lockers as $locker){
		?>
		<div class="locker">
			<div class="locker_id"><?=str_pad($locker['lockerId'],4,'0',STR_PAD_LEFT)?></div>
			<div class="floor"><?=htmlspecialchars($locker['floor'] ? $locker['floor'] : '[no name]')?></div>
			<div class="section"><?=htmlspecialchars($locker['section']? $locker['section'] : '[no name]')?></div>
			<div class="block"><?=htmlspecialchars($locker['block']? $locker['block'] : '[no name]')?></div>
			<div class="status"><?=($locker['status'] ? $locker['status'] : '[empty]')?></div>
			<div class="order_count"><?=($locker['orders']*1)?></div>
			<div class="release"><?=$locker['release']?></div>
			<a class="edit" href="/admin/locker/locker_id/<?=$locker['lockerId']?>">edit</a>
		</div>
		<?php
	}
	//Zend_Debug::dump($this->lockers);

?>
<hr />
<div>
	<a class="button" target="_blank" href="?do=printcodes">Print koder til skabe</a>
	<a class="button" href="#" onclick="$('reserve_form').reveal();$(this).hide();new Event(event).preventDefault();">Reserver alle skabe</a>
	<form method="POST" id="reserve_form" action="" style="display:none" class="search_form">
		<input type="hidden" name="do" value="reserve" />
		<button type="submit">Reserver</button>
		<div class="bfc">
			<input type="text" name="until" value="" placeholder="format:YYYY-mm-dd HH:mm:ss" />
		</div>

	</form>
</div>

<form method="GET" action="/admin/lockers" class="search_form" style="">

	<button type="submit">Søg</button>
	<div class="bfc"><input type="text" placeholder="fx. 1234 eller 1234-1456" name="search"/>
	</div>
</form>
